### ISSUE TITLE
Component nog working with hass 0.93

### ISSUE THREAD

**Issue by reharmsen** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#13]
I just ran a config_check for my configuration against hass 0.93.

Unfortunately I get the following error. When I disable the component in my configuration the check passes without warnings or errors.

IS this fixable in order to get the component to work with hass 0.93?

```
Failed config
  General Errors: 
    - Platform not found: sensor.afvalwijzer
```

**Comment by reharmsen** [comment]
relevant part of config

```yaml
sensor:
  - platform: afvalwijzer
    postcode: !secret postcode
    huisnummer: !secret huisnummer
```
