### ISSUE TITLE
Sensors not showing up

### ISSUE THREAD

**Issue by TOAOQ** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#62]
New to Home Assistant, running it as Docker on my Asustor.
I have added HACS, and after it showed up, I added this sensor.
Restarted it, and added the code in my config.yaml, tested it ( is OK) and restrted HASS.

Maybe I am missing something, but I cannot find the sensor under Entities, or am able to add it somehow in my overview (sensor cannot be selected when adding an Entity or Sensor card.

How can I make the sensor visible?

Thanks in advance!

**Comment by TOAOQ** [comment]
**System Health**
arch | x86_64
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.14.x
python_version | 3.7.7
timezone | Europe/Amsterdam
version | 0.109.3
virtualenv | false

**Afvalwijzer version 4.2.0**

**Log Details (ERROR)** 
Logger: homeassistant.setup
Source: setup.py:178
First occurred: 12:20:45 PM (1 occurrences)
Last logged: 12:20:45 PM
Setup failed for afvalwijzer: No setup function defined.

**Comment by TOAOQ** [comment]
Never mind..... got the sensors set-up (trial and error troubleshooting, somewhere I used a capital A for afvalwijzer.

How to apply the INPUT BOOLEAN (FOR AUTOMATION) and AUTOMATION code?

**Comment by TOAOQ** [comment]
please close, now looking in how to get the visuals like yours:

https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer/blob/master/afvalwijzer_lovelace.png

**Comment by TOAOQ** [comment]
Great platform to play with but am unable to set custom friendly names (they keep restoring to their defaults somehow). When checking in the Entities screen, trying to edit one of the sensors it states:

This entity does not have a unique ID, therefore its settings cannot be managed from the UI.

Is the same for all the sensor.trash* entities

Can someone please explain how I can set a custom friendly name?

**Comment by TOAOQ** [comment]
I was able to create:
![image](https://user-images.githubusercontent.com/40427096/81067430-ef7c3500-8ede-11ea-9699-c17e9ee78dee.png)
But not near as nice looking as what you have in the example, how to get that?

**Comment by xirixiz** [comment]
Hi TOAQQ, maybe this will help: 
```
https://github.com/xirixiz/my-hass-config/tree/master/www/afvalwijzer
https://github.com/xirixiz/my-hass-config/blob/master/packages/trash.yaml
```

**Comment by xirixiz** [comment]
Lovelace:

```
cards:
  - cards:
      - entity: sensor.trash_today_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.trash_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.trash_day_after_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
    type: horizontal-stack
  - card:
      type: glance
    filter:
      include:
        - entity_id: sensor.trash_gft
        - entity_id: sensor.trash_papier
        - entity_id: sensor.trash_pmd
        - entity_id: sensor.trash_restafval
    sort:
      attribute: next_pickup_in_days
      method: attribute
      numeric: true
    type: 'custom:auto-entities'
  - entities:
      - sensor.trash_first_next_in_days
      - style:
          background: '#62717b'
          height: 1px
          margin-left: auto
          margin-right: auto
        type: divider
      - input_boolean.trash_moved
      - input_boolean.trash_reminder
    show_header_toggle: false
    type: entities
type: vertical-stack
```

**Comment by TOAOQ** [comment]
Thanks!, next to being a newbie with HASS, YAML is new to me as well. Had some issues with provided codes but found out copy/paste into my editor sometimes created some extra spaces.....
Never too old to learn new tricks 👍 
Will look into it more tomorrow, also ran into an error because of notify.family (know now what to put into the config :)

**Comment by xirixiz** [comment]
You’ll learn by trial and error ✌🏻. Feel free to ask for help any time. Don’t forget the hass community. Useful information and help can be found there as well.

**Comment by xirixiz** [comment]
Good luck! I`ll close this question.

**Comment by TOAOQ** [comment]
Thanks again. Works great now! Also got the notifications working to my phone and tablet and changed some layout settings.

**Comment by xirixiz** [comment]
Great! Maybe you can share your code and layout as well!

**Comment by TOAOQ** [comment]
Haha, nothing fancy... switched the top and middle row of your card layout 😄 
Also re-organized the config.yaml, looked into and applied the !secret option to make the config.yaml more AVG proof 😉. 

Now trying to figure out why my TV won't turn on when sending a wake-on-lan request, and  how to get channel-up and channel-down buttons in the media-control card 🤔 (The next and previous buttons don't work for me as Live recording is enabled all the time)

Small steps into HASS and YAML, but fun

**Comment by xirixiz** [comment]
I used to have almost everything automated/managed by hass, but it was hard to maintain and I found out I didn't make use of a lot of functions. Just saying so you're aware not trying to add everything to hass. Add the things which really help making your life more easy 😄. Happy hassing!

**Comment by TOAOQ** [comment]
Haha, been there with Domoticz😄. Thing with the TV is that it doesn't work in other systems as well so I guess it's LG related. Seems the TV doesn't accept WoL and can work around that by using HDMI-CEC and turn on the Home Theater first which will trigger the TV
 
For the TV, and other media devices I have a separate tab/screen in mind to have a single remote option I can use on an older tablet.  Now use 4 different apps to control 6 devices (instead of their remotes)

**Comment by xirixiz** [comment]
Do you have it running in Docker? Which WebOS version are you using (or TV ?

In the past I used something like this, which eventually worked, but only running hass in Docker on the host network.

```
media_player:
  - platform: webostv
    host: 192.168.xxx.yyy
    name: LG TV
    timeout: 5
    turn_on_action:
      service: switch.turn_on
      entity_id: switch.lg

switch:
  - platform: wake_on_lan
    name: lg
    mac_address: "aa:bb:cc:dd:ee:ff"
```
