### ISSUE TITLE
Geen sensors

### ISSUE THREAD

**Issue by sand3rk** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#65]
Krijg geen sensors van afvalwijzer. Ik doe vast iets fout. Ook geen notificatie met fout inladen na herstart HA.

Home Assistant Core
Geinstalleerd met hacs.

Toegevoegd aan configuration.yaml:
```
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    zipcode: 1906KD
    housenumber: 17
```
https://mijnafvalwijzer.nl/nl/1906KD/17/

**Comment by JBS5** [comment]
Heb je in je _configuration.yaml_ op een andere plek ook nog `sensor:` gevolgd door sensoren staan?
`sensor:` neem je maar één keer op je configuration.yaml en daaronder voeg je al je sensoren toe.

**Comment by sand3rk** [comment]
> 
> 
> Heb je in je _configuration.yaml_ op een andere plek ook nog `sensor:` gevolgd door sensoren staan?
> `sensor:` neem je maar één keer op je configuration.yaml en daaronder voeg je al je sensoren toe.
Nee, heb ik niet.
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
python_script:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
panel_iframe:
  portainer:
    title: 'Portainer'
    url: 'http://192.168.100.10:9000'
    icon: mdi:raspberry-pi
  esphome:
    title: 'ESPHome'
    url: 'http://192.168.100.10:6052'
    icon: mdi:raspberry-pi
  nodered:
    title: 'Node-Red'
    url: 'http://192.168.100.10:1880'
    icon: mdi:sitemap
  unifi:
    title: 'Unifi controller'
    url: 'http://192.168.100.10:8080'
    icon: mdi:raspberry-pi
  adguardhome:
    title: 'Adguard Home'
    url: 'http://192.168.100.10:3000'
    icon: mdi:raspberry-pi

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'time_date'
  - platform: template
    sensors:
      date_template:
        friendly_name: 'Date'
        entity_id: sensor.time_date
        value_template: "{{ as_timestamp(now()) | timestamp_custom('%H:%M - %d %B %Y') }}"
  - platform: template
    sensors:
      nextsunrise:
        entity_id: sun.sun
        friendly_name: 'Zonsopgang'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %H:%M ') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        entity_id: sun.sun
        friendly_name: 'Zonsondergang'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %H:%M ') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    zipcode: 1906KD
    housenumber: 17
```
